-- Seed data for audit logs (repeatable migration)
-- This file will be executed on every migration run after the initial setup

-- Clear existing audit logs
DELETE FROM audit_logs;

-- Insert sample audit log entries
-- These use hardcoded UUIDs for demonstration purposes
-- In production, these would be generated by actual system actions

-- Sample member-related audit logs
INSERT INTO audit_logs (member_id, entity_id, entity_type, action, description, created_at)
SELECT 
  m.id,
  m.id,
  'member',
  'CREATE',
  'Created member account for ' || m.firstname || ' ' || m.lastname,
  NOW() - INTERVAL '30 days'
FROM members m
WHERE m.email = 'john.doe@example.com'
LIMIT 1;

INSERT INTO audit_logs (member_id, entity_id, entity_type, action, description, created_at)
SELECT 
  m.id,
  m.id,
  'member',
  'UPDATE',
  'Updated profile information for ' || m.firstname || ' ' || m.lastname,
  NOW() - INTERVAL '25 days'
FROM members m
WHERE m.email = 'john.doe@example.com'
LIMIT 1;

-- Sample trainer-related audit logs
INSERT INTO audit_logs (member_id, entity_id, entity_type, action, description, created_at)
SELECT 
  m.id,
  t.member_id,
  'trainer',
  'CREATE',
  'Promoted ' || m.firstname || ' ' || m.lastname || ' to trainer',
  NOW() - INTERVAL '15 days'
FROM members m
INNER JOIN trainers t ON m.id = t.member_id
LIMIT 1;

-- Sample plan-related audit logs
INSERT INTO audit_logs (member_id, entity_id, entity_type, action, description, created_at)
SELECT 
  (SELECT m.id FROM members m INNER JOIN trainers t ON m.id = t.member_id LIMIT 1),
  p.id,
  'plan',
  'CREATE',
  'Created subscription plan: ' || p.name,
  NOW() - INTERVAL '40 days'
FROM plans p
LIMIT 1;

INSERT INTO audit_logs (member_id, entity_id, entity_type, action, description, created_at)
SELECT 
  (SELECT m.id FROM members m INNER JOIN trainers t ON m.id = t.member_id LIMIT 1),
  p.id,
  'plan',
  'UPDATE',
  'Updated pricing for plan: ' || p.name,
  NOW() - INTERVAL '35 days'
FROM plans p
LIMIT 1;

-- Sample subscription-related audit logs
INSERT INTO audit_logs (member_id, entity_id, entity_type, action, description, created_at)
SELECT 
  s.member_id,
  s.id,
  'subscription',
  'CREATE',
  'Created new subscription',
  NOW() - INTERVAL '28 days'
FROM subscriptions s
LIMIT 1;

INSERT INTO audit_logs (member_id, entity_id, entity_type, action, description, created_at)
SELECT 
  s.member_id,
  s.id,
  'subscription',
  'UPDATE',
  'Updated subscription plan',
  NOW() - INTERVAL '14 days'
FROM subscriptions s
LIMIT 1;

-- Generate additional sample audit logs for testing pagination
INSERT INTO audit_logs (member_id, entity_id, entity_type, action, description, created_at)
SELECT 
  (SELECT id FROM members LIMIT 1),
  gen_random_uuid(),
  CASE (gs.i % 5)
    WHEN 0 THEN 'member'
    WHEN 1 THEN 'subscription'
    WHEN 2 THEN 'plan'
    WHEN 3 THEN 'payment'
    ELSE 'equipment'
  END,
  CASE (gs.i % 3)
    WHEN 0 THEN 'CREATE'
    WHEN 1 THEN 'UPDATE'
    ELSE 'DELETE'
  END,
  'Sample audit log entry ' || gs.i,
  NOW() - gs.i * INTERVAL '1 hour'
FROM generate_series(1, 50) AS gs(i);

